chore: fix CI/CD badges in README
siddhantgoel/streaming-form-data pull request #74
Opened 2023-04-20 08:08 UTC by jasopolis

2023-04-20 18:09 UTC, siddhantgoel requested changes

2023-04-20 18:09 UTC, siddhantgoel commented on README.md
> +[![image](https://github.com/siddhantgoel/streaming-form-data/actions/workflows/test.yml/badge.svg)](https://github.com/siddhantgoel/streaming-form-data/actions/workflows/test.yml) [![image](https://
If you could break this into multiple lines it would be much easier to read!

2023-04-20 18:30 UTC, jasopolis commented on README.md
> +[![image](https://github.com/siddhantgoel/streaming-form-data/actions/workflows/test.yml/badge.svg)](https://github.com/siddhantgoel/streaming-form-data/actions/workflows/test.yml) [![image](https://
Sure, dropped that commit: https://github.com/jasopolis/streaming-form-data/blob/patch-1/README.md

2023-04-21 16:12 UTC, siddhantgoel approved these changes

2023-04-21 16:13 UTC, merged