S3Target via Smart OPen
siddhantgoel/streaming-form-data pull request #76
Opened 2023-04-23 20:30 UTC by tokicnikolaus

Implement S3 target using smart_open library that will upload files to the S3 in chunks under the hood.

2023-04-23 20:38 UTC, tokicnikolaus commented
Hi @siddhantgoel, 
I used this S3target in my project, which might be useful for others also. 

Used smart_open library since it will do the upload in chunks. Boto3 doesn't have the option to do the direct stream, at least I couldn't find it.

Let me know what you think.

2023-04-30 13:50 UTC, siddhantgoel requested changes
Awesome, TIL about `smart_open`! I like how simple it makes implementing such an S3 target.

I've left some minor comments on the target class and would love to have the test written using the pytest style. Otherwise I'm looking forward to merging and releasing this soon!

2023-04-30 13:50 UTC, siddhantgoel commented on streaming_form_data/targets.py
> +        self._f_out = None
Let's rename this to `self._fd` to keep things consistent with the other targets (eg. `FileTarget`).

2023-04-30 13:50 UTC, siddhantgoel commented on streaming_form_data/targets.py
> +        self.data_received_size = 0
We're not really using this variable. I wonder if we can get rid of it?

2023-04-30 13:50 UTC, siddhantgoel commented on tests/test_targets.py
> +class TestS3TargetUpload(TestCase):
Let's use `pytest` style tests written as plain functions. The `boto3` client and `mock_s3` could be added as fixtures that the test function makes use of.

```python
def test_s3_upload(mock_s3, mock_client):
  ...
```

2023-05-02 12:58 UTC, tokicnikolaus commented on streaming_form_data/targets.py
> +        self.data_received_size = 0
I was using it in my project, but it can be removed yes.

2023-05-02 12:58 UTC, tokicnikolaus commented on tests/test_targets.py
> +class TestS3TargetUpload(TestCase):
The test is changed, let me know if something else is required to be changed.

2023-05-02 18:57 UTC, tokicnikolaus commented
@siddhantgoel Thanks for the feedback, I changed it based on your comments, please check  it again and let me know if anything else is needed!

2023-05-04 07:56 UTC, tokicnikolaus commented
@siddhantgoel I think all linters are a bit happier now. Since I need to wait for you to allow the workflow to run, let me know if something more pops up!

2023-05-07 08:39 UTC, siddhantgoel commented
@tokicnikolaus thanks for the updates, but `black` is somehow still not happy. If you run `make lint` locally it should run all the linters and show you what's failing.

I'm also not sure why Github asks me to approve and run the workflow every time, but I have a bit more time on my hands at the moment so I should be able to click the button rather quickly now!

2023-05-09 12:45 UTC, siddhantgoel commented
Thanks! It seems like now pytest is complaining about a missing dependency. You can run `make pip-compile` to update `requirements.txt` after which it should go through.

2023-05-09 19:17 UTC, siddhantgoel approved these changes

2023-05-09 19:18 UTC, siddhantgoel commented
@tokicnikolaus awesome, looks like everything's green now! I'll merge this and try to publish a release in the next days.

2023-05-09 19:18 UTC, merged

2023-05-13 10:45 UTC, siddhantgoel commented
Just published v1.12.0 which includes this feature. Thanks for your work on this!