Draft: introduce strict mode
siddhantgoel/streaming-form-data pull request #88
Opened 2023-09-11 21:41 UTC by hbusul

I've added a first draft of the strict mode, to sum up the changes:

In `parser.py` I've added `UnregisteredPartException` which is a subclass of the `ParseFailedException`.
It has an additional field `part_name` so you can get what was the name of the unregistered field.

`StreamingFormDataParser` init function has an extra keyword argument `strict` which defaults to `False`.
And it passes this argument to ctor of `_Parser`.

In pyx file. I've added a new number in `ErrorGroup`. `_Parser` has 2 new fields, `strict` and `unknown_part`.
The latter one is public, ctor sets the strict mode. And when we are switching the active target, if the new
target is an unregistered one, we set `unknown_part` , `mark_error` and return new code from the enum.

@siddhantgoel I would appreciate if you could take a look at it :)

2023-09-12 16:52 UTC, siddhantgoel requested changes
Overall looks like it'll work! Just left some minor naming suggestions and looks like the CI needs to be made green to be able to merge this in.

2023-09-12 16:52 UTC, siddhantgoel commented on streaming_form_data/parser.py
> +        self.part_name = part_name
Let's rename this to `UnexpectedPartException` to also be consistent with `parser.unexpected_part_name` as mentioned in the other comment.

2023-09-12 16:52 UTC, siddhantgoel commented on streaming_form_data/parser.py
> +            elif ErrorGroup.UnregisteredPart <= result:
```suggestion
            elif ErrorGroup.UnregisteredPart == result:
```

Background: I think I might rework the `ErrorGroup` system to return specific codes for specific errors so we don't have to do `<= result <` style range checks. At the moment those ranges are arbitrary anyway and don't really let the client know what went wrong. So this suggestion would make that work somewhat easier. :)

2023-09-12 16:52 UTC, siddhantgoel commented on streaming_form_data/_parser.pyx
> +        self.unknown_part = ''
```suggestion
        self.unexpected_part_name = ''
```

It's a nitpick but in the rest of the parser we're using `expected_parts` terminology, so just to make things consistent. :)

2023-09-12 16:52 UTC, siddhantgoel commented on streaming_form_data/_parser.pyx
> +    UnregisteredPart = 400
```suggestion
    UnexpectedPart = 400
```

2023-09-12 17:34 UTC, hbusul commented
> Overall looks like it'll work! Just left some minor naming suggestions and looks like the CI needs to be made green to be able to merge this in.

I'm testing locally with flask to see if I get the exception. I've done the changes you have mentioned. I guess still documentation and tests are missing.  I guess I should also write documentation and tests right? It would be nice to mention in the documentation this `ParseFailedException` as well in addition to `UnexpectedPartException`

2023-09-12 19:42 UTC, siddhantgoel commented
>  I guess still documentation and tests are missing. I guess I should also write documentation and tests right? It would be nice to mention in the documentation this ParseFailedException as well in addition to UnexpectedPartException

Yeah, maybe another section in `docs/index.rst` and at least one parser test to make sure that the exception is raised in strict mode.

2023-09-13 00:53 UTC, hbusul commented
I've added some docs and a test for testing the strict mode

2023-09-13 06:43 UTC, siddhantgoel commented
Awesome, looks good to me! I'll merge it in and try to push a release by the coming weekend.

2023-09-13 06:44 UTC, siddhantgoel approved these changes

2023-09-13 06:44 UTC, merged

2023-09-19 13:43 UTC, hbusul commented
@siddhantgoel sorry to bother but did you have a chance to look at the release? Cause I would really like to use this library :D

2023-09-19 18:10 UTC, siddhantgoel commented
No worries, thanks for the reminder as I had completely forgotten about this, so sorry about that!

But v1.13.0 should be available on PyPI now!

2023-09-19 20:39 UTC, hbusul commented
yes it is there, thanks a lot!